#!/usr/bin/env python3
"""Select filtered crawl videos and build train/eval split maps.

This utility consumes ``vlm_filter_report.json`` generated by
``scripts/batch_filter.py`` and materializes a new dataset version under
``cluster_data``.  It intentionally does not overwrite the existing train50 /
eval20 split, so old experiments remain reproducible.

Example:

  python scripts/data/select_crawl_videos.py \
    --report /path/to/crawl_run/vlm_filter_report.json \
    --data-root cluster_data \
    --dataset-name extra100 \
    --train-count 80 \
    --eval-count 20 \
    --mode transcode \
    --exclude-map cluster_data/splits/train_videos.json \
    --exclude-map cluster_data/splits/eval_videos.json

Default behavior also scans ``cluster_data/videos`` and ``cluster_data/splits``
to deduplicate against all existing videos.  ``--mode transcode`` converts the
selected files to Qwen3/OpenCV-friendly H.264/yuv420p/AAC ``.mp4`` files.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any


VIDEO_EXTS = {".mp4", ".webm", ".mkv", ".avi", ".mov"}
KEEP_DECISIONS = {"保留", "需要裁剪"}


def load_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def load_excluded_ids(paths: list[Path]) -> set[str]:
    ids: set[str] = set()
    for path in paths:
        if not path.exists():
            continue
        payload = load_json(path)
        if isinstance(payload, dict):
            ids.update(str(k) for k in payload.keys())
            ids.update(Path(str(v)).stem for v in payload.values())
    return ids


def scan_existing_video_ids(data_root: Path) -> set[str]:
    """Collect existing video ids under data_root/videos and data_root/splits."""
    ids: set[str] = set()
    videos_dir = data_root / "videos"
    if videos_dir.exists():
        for path in videos_dir.rglob("*"):
            if path.is_file() and path.suffix.lower() in VIDEO_EXTS:
                ids.add(path.stem)

    splits_dir = data_root / "splits"
    if splits_dir.exists():
        for path in splits_dir.glob("*_videos.json"):
            try:
                ids.update(load_excluded_ids([path]))
            except Exception as exc:  # noqa: BLE001
                print(f"[warn] failed to read split map {path}: {exc}")
    return ids


def resolve_video_path(raw_path: str, report_path: Path) -> Path:
    path = Path(raw_path)
    if path.exists():
        return path.resolve()

    # batch_filter usually stores paths relative to the invocation CWD, while
    # the report lives at <crawl_run>/vlm_filter_report.json.
    candidates = [
        report_path.parent / raw_path,
        report_path.parent / "media" / raw_path,
        Path.cwd() / raw_path,
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate.resolve()

    return path


def rank_candidates(report: dict[str, Any], report_path: Path, excluded_ids: set[str]) -> list[dict[str, Any]]:
    candidates = []
    for rec in report.get("videos", []):
        video_id = str(rec.get("video_id") or "").strip()
        if not video_id or video_id in excluded_ids:
            continue

        decision = str(rec.get("决策") or "").strip()
        if decision not in KEEP_DECISIONS:
            continue

        video_path = resolve_video_path(str(rec.get("video_path") or ""), report_path)
        if video_path.suffix.lower() not in VIDEO_EXTS or not video_path.exists():
            continue

        candidates.append({
            "video_id": video_id,
            "video_path": video_path,
            "decision": decision,
            "quality": int(rec.get("质量评分") or 0),
            "duration_sec": float(rec.get("duration_sec") or 0.0),
            "category": str(rec.get("category") or video_path.parent.name),
        })

    # Prefer clear keep decisions, then higher quality, then longer usable videos.
    candidates.sort(
        key=lambda x: (
            1 if x["decision"] == "保留" else 0,
            x["quality"],
            x["duration_sec"],
            x["video_id"],
        ),
        reverse=True,
    )
    return candidates


def transcode_to_qwen3_mp4(src: Path, dst: Path, *, ffmpeg_bin: str, crf: int, preset: str) -> None:
    """Transcode to H.264/yuv420p/AAC MP4 for Qwen3/OpenCV compatibility."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    tmp = dst.with_name(f"{dst.stem}.tmp{dst.suffix}")
    tmp.unlink(missing_ok=True)
    cmd = [
        ffmpeg_bin,
        "-nostdin",
        "-y",
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        str(src),
        "-map",
        "0:v:0",
        "-map",
        "0:a?",
        "-c:v",
        "libx264",
        "-preset",
        preset,
        "-crf",
        str(crf),
        "-pix_fmt",
        "yuv420p",
        "-movflags",
        "+faststart",
        "-c:a",
        "aac",
        "-b:a",
        "128k",
        str(tmp),
    ]
    print(f"[transcode] {src} -> {dst}")
    result = subprocess.run(cmd, stdin=subprocess.DEVNULL, text=True)
    if result.returncode != 0:
        tmp.unlink(missing_ok=True)
        raise RuntimeError(f"ffmpeg failed: {src}")
    tmp.replace(dst)


def materialize(src: Path, dst: Path, mode: str, *, ffmpeg_bin: str, crf: int, preset: str) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        return

    if mode == "copy":
        shutil.copy2(src, dst)
    elif mode == "symlink":
        os.symlink(src, dst)
    elif mode == "transcode":
        transcode_to_qwen3_mp4(src, dst, ffmpeg_bin=ffmpeg_bin, crf=crf, preset=preset)
    else:
        raise ValueError(f"Unknown mode: {mode}")


def write_split(rows: list[dict[str, Any]], video_dir: Path, split_name: str, splits_dir: Path) -> dict[str, str]:
    splits_dir.mkdir(parents=True, exist_ok=True)
    mapping = {
        row["video_id"]: str(video_dir / f"{row['video_id']}.mp4")
        for row in rows
    }

    (splits_dir / f"{split_name}_videos.json").write_text(
        json.dumps(mapping, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    with (splits_dir / f"{split_name}_videos.tsv").open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(
                f"{row['video_id']}\t{mapping[row['video_id']]}\t"
                f"{row['decision']}\t{row['quality']}\t{row['duration_sec']:.1f}\t{row['category']}\n"
            )
    return mapping


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Select filtered crawl videos into a versioned dataset")
    parser.add_argument("--report", type=Path, required=True, help="Path to vlm_filter_report.json")
    parser.add_argument("--data-root", type=Path, default=Path("cluster_data"))
    parser.add_argument("--dataset-name", type=str, default="extra100")
    parser.add_argument("--train-count", type=int, default=80)
    parser.add_argument("--eval-count", type=int, default=20)
    parser.add_argument(
        "--mode",
        choices=["symlink", "copy", "transcode"],
        default="transcode",
        help="transcode writes Qwen3/OpenCV-friendly H264/yuv420p/AAC .mp4 files.",
    )
    parser.add_argument("--exclude-map", type=Path, action="append", default=[])
    parser.add_argument("--no-scan-existing", action="store_true", help="Do not auto-exclude existing videos under data-root")
    parser.add_argument("--ffmpeg-bin", default="ffmpeg")
    parser.add_argument("--crf", type=int, default=23)
    parser.add_argument("--preset", default="veryfast")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    report_path = args.report.resolve()
    report = load_json(report_path)
    excluded_ids = load_excluded_ids(args.exclude_map)
    if not args.no_scan_existing:
        existing_ids = scan_existing_video_ids(args.data_root)
        excluded_ids.update(existing_ids)
        print(f"[dedupe] auto-excluding {len(existing_ids)} existing video ids under {args.data_root}")

    total_needed = args.train_count + args.eval_count
    candidates = rank_candidates(report, report_path, excluded_ids)
    selected = candidates[:total_needed]
    if len(selected) < total_needed:
        raise RuntimeError(f"Only found {len(selected)} usable videos, need {total_needed}")

    train_rows = selected[:args.train_count]
    eval_rows = selected[args.train_count:total_needed]

    train_split = f"train_{args.dataset_name}"
    eval_split = f"eval_{args.dataset_name}"
    train_dir = args.data_root / "videos" / train_split
    eval_dir = args.data_root / "videos" / eval_split
    splits_dir = args.data_root / "splits"

    for row in train_rows:
        materialize(
            row["video_path"],
            train_dir / f"{row['video_id']}.mp4",
            args.mode,
            ffmpeg_bin=args.ffmpeg_bin,
            crf=args.crf,
            preset=args.preset,
        )
    for row in eval_rows:
        materialize(
            row["video_path"],
            eval_dir / f"{row['video_id']}.mp4",
            args.mode,
            ffmpeg_bin=args.ffmpeg_bin,
            crf=args.crf,
            preset=args.preset,
        )

    train_map = write_split(train_rows, train_dir, train_split, splits_dir)
    eval_map = write_split(eval_rows, eval_dir, eval_split, splits_dir)

    manifest = {
        "dataset_name": args.dataset_name,
        "report": str(report_path),
        "mode": args.mode,
        "excluded_ids": sorted(excluded_ids),
        "train_split": train_split,
        "eval_split": eval_split,
        "train_count": len(train_map),
        "eval_count": len(eval_map),
        "train_videos_json": str(splits_dir / f"{train_split}_videos.json"),
        "eval_videos_json": str(splits_dir / f"{eval_split}_videos.json"),
    }
    manifest_path = splits_dir / f"{args.dataset_name}_manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()